server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: boot-user-service-provider
  #需要将order-service这个服务，注册到本地8848的注册中心上去，所以我们需要指定注册中心的地址
  cloud:
    nacos:
#     注册中心 也就是连接到哪个nacos上
      discovery:
        server-addr: localhost:8848

#       如果使用域名的注册中心地址时，域名后面需要加80端口，否则服务注册不上去，要注意
#        server-addr: nacos.it235.com:80

#        将自己的服务注册到注册中心
        register-enabled: true
        namespace: b93daaf8-adae-4dc9-bf47-a812c650fd21
      #     配置中心
      config:
        server-addr: localhost:8848
#        配置格式
        file-extension: yaml
        prefix: custom-prefix
        namespace: b93daaf8-adae-4dc9-bf47-a812c650fd21

dubbo:
  protocol:
    port:
      20881
  registry:
    address: nacos://127.0.0.1:8848
