server:
  port: 8080

logging:
  level:
    root: info
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  #OAuth2.0第三方登录配置
  security:
    oauth2:
      client:
        registration:
          gitee:
            ##替换成你自己的App密钥
            client-id: xxx
            client-secret: xxx
          #          github:
          #            ##替换成你自己的App密钥
          #            client-id: xxx
          #            client-secret: xxx
          ## 使用自定义的OAuth2.0授权登录服务
          goodskill:
            ##替换成你自己的App密钥
            client-id: second-client
            client-secret: noonewilleverguess
